import {
  browserName,
  browserVersion,
  deviceType,
  engineName,
  engineVersion,
  isBrowser,
  isChrome,
  isChromium,
  isConsole,
  isDesktop,
  isEdge,
  isEdgeChromium,
  isElectron,
  isEmbedded,
  isFirefox,
  isIE,
  isIOS,
  isIOS13,
  isIPad13,
  isIPhone13,
  isIPod13,
  isMacOs,
  isMIUI,
  isMobile,
  isMobileOnly,
  isMobileSafari,
  isOpera,
  isSafari,
  isSamsungBrowser,
  isSmartTV,
  isTablet,
  isWearable,
  isWinPhone,
  isYandex,
  mobileModel,
  mobileVendor,
} from "react-device-detect";

export const browsers = {
  browserName: browserName,
  browserVersion: browserVersion,
  deviceType: deviceType,
  engineName: engineName,
  engineVersion: engineVersion,
  isBrowser: isBrowser,
  isChrome: isChrome,
  isChromium: isChromium,
  isConsole: isConsole,
  isDesktop: isDesktop,
  isEdge: isEdge,
  isEdgeChromium: isEdgeChromium,
  isElectron: isElectron,
  isEmbedded: isEmbedded,
  isFirefox: isFirefox,
  isIE: isIE,
  isIOS: isIOS,
  isIOS13: isIOS13,
  isIPad13: isIPad13,
  isIPhone13: isIPhone13,
  isIPod13: isIPod13,
  isMacOs: isMacOs,
  isMIUI: isMIUI,
  isMobile: isMobile,
  isMobileOnly: isMobileOnly,
  isMobileSafari: isMobileSafari,
  isOpera: isOpera,
  isSafari: isSafari,
  isSamsungBrowser: isSamsungBrowser,
  isSmartTV: isSmartTV,
  isTablet: isTablet,
  isWearable: isWearable,
  isWinPhone: isWinPhone,
  isYandex: isYandex,
  mobileModel: mobileModel,
  mobileVendor: mobileVendor,
};
